<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validateTokenAndGetData</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required secretKey</value>
    <value>[i] field:0:required jwtToken</value>
    <value>[o] recref:0:required output IXCommon.documents:JWTResponse</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCgkJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCgkJCVN0cmluZwlzZWNyZXRLZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgInNlY3JldEtleSIgKTsNCgkJCVN0cmluZwlqd3RUb2tlbiA9IElEYXRhVXRp
bC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiand0VG9rZW4iICk7DQoJCXBpcGVsaW5lQ3Vy
c29yLmRlc3Ryb3koKTsNCgkJU3RyaW5nIGVycm9yID0iIjsNCgkJIE1hcDxTdHJpbmcsIE9iamVj
dD4gY2xhaW1zRGF0YT1uZXcgSGFzaE1hcDxTdHJpbmcsIE9iamVjdD4oKTsNCgkgICB0cnl7DQov
LwkJCQlQdWJsaWNLZXkgcHVibGljS2V5ID0gZ2V0UHVibGljS2V5KHNlY3JldEtleSk7DQoJCSAg
IA0KDQoJCSAgIGNsYWltc0RhdGEgPSBuZXcgSGFzaE1hcDw+KHZhbGlkYXRlVG9rZW4oand0VG9r
ZW4sIHNlY3JldEtleSkpOw0KCQkgICANCgkJICAgLy9kYXRhID12YWxpZGF0ZVRva2VuKGp3dFRv
a2VuLCBzZWNyZXRLZXkgKTsNCgkJLy9JRGF0YVtdCXVzZXJEYXRhID0gbnVsbDsNCgkJDQoJCQ0K
CSAgIH1jYXRjaChFeGNlcHRpb24gZSkgew0KCQkJLy8gVE9ETzogaGFuZGxlIGV4Y2VwdGlvbg0K
CQkJLy90b2tlbiA9IGUuZ2V0TG9jYWxpemVkTWVzc2FnZSgpOw0KCQkJU3RyaW5nV3JpdGVyIHN3
ID0gbmV3IFN0cmluZ1dyaXRlcigpOw0KCQkJUHJpbnRXcml0ZXIgcHcgPSBuZXcgUHJpbnRXcml0
ZXIoc3cpOw0KCQkJZS5wcmludFN0YWNrVHJhY2UocHcpOw0KCQkJZXJyb3IgPSBzdy50b1N0cmlu
ZygpOw0KCSAgIH0NCgkvLyBwaXBlbGluZQ0KCQlJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8x
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJCUlEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5j
cmVhdGUoKTsNCgkJSURhdGFDdXJzb3Igb3V0cHV0Q3Vyc29yID0gb3V0cHV0LmdldEN1cnNvcigp
Ow0KCQkNCgkJZm9yKEVudHJ5PFN0cmluZywgT2JqZWN0PiBlbnRyeSA6IGNsYWltc0RhdGEuZW50
cnlTZXQoKSkgew0KCSAgICAgICAvLyBleHBlY3RlZE1hcC5wdXQoZW50cnkuZ2V0S2V5KCkgLCBl
bnRyeS5nZXRWYWx1ZSgpKTsNCgkgICAgICAgIElEYXRhVXRpbC5wdXQoIG91dHB1dEN1cnNvciwg
ZW50cnkuZ2V0S2V5KCksIGVudHJ5LmdldFZhbHVlKCkgKTsNCgkgICAgfQ0KCQlvdXRwdXRDdXJz
b3IuZGVzdHJveSgpOw0KCQkvL0lEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJpc1Zh
bGlkIiwgIiIgKTsNCgkJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgIm91dHB1dCIs
IG91dHB1dCApOw0KCQlJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZXJyb3IiLCBl
cnJvciApOw0KCQlwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCgkNCg==</value>
</Values>
